"""initial schema

Every table from CLAUDE.md §4. Two objects here are NOT autogenerated and must survive any
regeneration of this file:

* ``uq_totes_user_code_lower`` — a functional unique index on ``lower(code)``. The tote code is
  printed on a physical index card and encoded in an NFC tag, so "a14" and "A14" being two
  different bins is a real-world ambiguity, not a data-cleanliness nicety. SQLAlchemy cannot
  express a functional index as a table-level UniqueConstraint, so it lives only here.
* ``ix_items_search_vector`` — the GIN index that makes the app's primary query path ("where is
  the ratchet set") an index scan rather than a sequential one. The column itself is a STORED
  generated column, which autogenerate DOES emit; the index is not.

Revision ID: 87ad8924b20f
Revises: 
Create Date: 2026-08-15 23:36:01.735719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_categories_user_name')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_locations_user_name')
    )
    op.create_index(op.f('ix_locations_user_id'), 'locations', ['user_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_user_id'), 'people', ['user_id'], unique=False)
    op.create_table('person_sizes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('garment_type', sa.String(length=16), nullable=False),
    sa.Column('size_raw', sa.String(length=32), nullable=False),
    sa.Column('size_system', sa.String(length=24), nullable=True),
    sa.Column('size_ordinal', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_sizes_person_id'), 'person_sizes', ['person_id'], unique=False)
    op.create_table('totes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('bin_kind', sa.String(length=48), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('nfc_tag_uid', sa.String(length=32), nullable=True),
    sa.Column('nfc_written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nfc_tag_uid', name='uq_totes_user_tag')
    )
    op.create_index(op.f('ix_totes_location_id'), 'totes', ['location_id'], unique=False)
    op.create_index(op.f('ix_totes_user_id'), 'totes', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_location_id', sa.Uuid(), nullable=True),
    sa.Column('nfc_uri_base', sa.String(length=255), nullable=True),
    sa.Column('ntfy_topic', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='stored', nullable=False),
    sa.Column('current_tote_id', sa.Uuid(), nullable=True),
    sa.Column('out_reason', sa.String(length=16), nullable=True),
    sa.Column('out_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_back', sa.Date(), nullable=True),
    sa.Column('value_est', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(notes, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_tote_id'], ['totes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_current_tote_id'), 'items', ['current_tote_id'], unique=False)
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_table('item_apparel',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('size_raw', sa.String(length=32), nullable=True),
    sa.Column('size_system', sa.String(length=24), nullable=True),
    sa.Column('size_ordinal', sa.Float(), nullable=True),
    sa.Column('department', sa.String(length=16), nullable=True),
    sa.Column('size_type', sa.String(length=16), nullable=True),
    sa.Column('color', sa.String(length=48), nullable=True),
    sa.Column('material', sa.String(length=96), nullable=True),
    sa.Column('style', sa.String(length=48), nullable=True),
    sa.Column('fit', sa.String(length=16), nullable=True),
    sa.Column('sleeve_length', sa.String(length=16), nullable=True),
    sa.Column('measurements_in', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('original_path', sa.String(length=255), nullable=False),
    sa.Column('cleaned_path', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_photos_item_id'), 'item_photos', ['item_id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('from_tote_id', sa.Uuid(), nullable=True),
    sa.Column('to_tote_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_tote_id'], ['totes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_tote_id'], ['totes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_item_id'), 'movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_movements_moved_at'), 'movements', ['moved_at'], unique=False)
    # ### end Alembic commands ###

    # --- Not autogenerated: see the module docstring ------------------------------------
    # Case-insensitive uniqueness for the tote code, per user.
    op.create_index(
        "uq_totes_user_code_lower",
        "totes",
        ["user_id", sa.text("lower(code)")],
        unique=True,
    )
    # Full-text search over items. GIN because search_vector is a tsvector and the query is
    # "does this document contain these lexemes" — a btree cannot answer that.
    op.create_index(
        "ix_items_search_vector",
        "items",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_items_search_vector", table_name="items")
    op.drop_index("uq_totes_user_code_lower", table_name="totes")
    op.drop_index(op.f('ix_movements_moved_at'), table_name='movements')
    op.drop_index(op.f('ix_movements_item_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_item_photos_item_id'), table_name='item_photos')
    op.drop_table('item_photos')
    op.drop_table('item_apparel')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_index(op.f('ix_items_current_tote_id'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_totes_user_id'), table_name='totes')
    op.drop_index(op.f('ix_totes_location_id'), table_name='totes')
    op.drop_table('totes')
    op.drop_index(op.f('ix_person_sizes_person_id'), table_name='person_sizes')
    op.drop_table('person_sizes')
    op.drop_index(op.f('ix_people_user_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_locations_user_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
