"""draft state for scanned items

READ THIS BEFORE RUNNING autogenerate AGAIN.

Autogenerate proposed dropping BOTH manual indexes from migration 0001:

    op.drop_index('ix_items_search_vector', ...)      # the GIN full-text index
    op.drop_index('uq_totes_user_code_lower', ...)    # unique on lower(code), per user

Both were deleted from this file by hand. Alembic cannot see either object in the model
metadata — a functional index and an explicitly-created GIN index are invisible to it — so it
concludes they are stray and helpfully offers to remove them.

Accepting that would have been silent and severe: search would still return correct results, just
by sequential scan, and two bins could both be labelled "A14"/"a14" with nothing to stop it. The
failure would surface months later as "search got slow" and "which A14 is this".

`test_schema.py` asserts both indexes exist at head, so this cannot land unnoticed again --- but
every future autogenerate will propose it, and every future migration must have these lines
removed by hand.

Revision ID: 1bc6a6aa0f58
Revises: 0001
Create Date: 2026-08-16 09:29:46.887674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('items', sa.Column('draft_tote_id', sa.Uuid(), nullable=True))
    op.add_column('items', sa.Column('scan_error', sa.String(length=32), nullable=True))
    op.add_column('items', sa.Column('scan_confidence', sa.String(length=8), nullable=True))
    op.add_column('items', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # NAMED, unlike what autogenerate produced. An unnamed constraint gets a Postgres-assigned
    # name that `downgrade` then cannot refer to, so `alembic downgrade` dies with
    # "Can't emit DROP CONSTRAINT ... it has no name" — a migration that only goes one way, which
    # is not a migration.
    op.create_foreign_key(
        "fk_items_draft_tote_id", "items", "totes", ["draft_tote_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_items_draft_tote_id", "items", type_="foreignkey")
    op.drop_column('items', 'processed_at')
    op.drop_column('items', 'scan_confidence')
    op.drop_column('items', 'scan_error')
    op.drop_column('items', 'draft_tote_id')
    op.drop_column('items', 'is_draft')
    # ### end Alembic commands ###
